---
linters:
  enable-all: true
  disable:
    - cyclop
    - durationcheck
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - goerr113
    - golint
    - gomnd
    - lll
    - nestif
    - noctx
    - nonamedreturns
    - paralleltest
    - revive
    - stylecheck
    - testpackage
    - usestdlibvars
    - varnamelen
    - wrapcheck
    - wsl
    #
    # The following linters have been deprecated
    #
    - maligned
    - ifshort
    - structcheck
    - exhaustivestruct
    - scopelint
    - deadcode
    - nosnakecase
    - interfacer
    - varcheck
