---
name: Release
'on':
  push:
    tags:
      - '*'
jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
        # yamllint disable rule:line-length
      - name: Set multipart deliverable environment variable
        run: |
          echo "multipart-deliverable=multipart-${{ matrix.os }}" >> $GITHUB_ENV
        if: |
          ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Set multipart deliverable environment variable on Windows
        run: |
          echo "multipart-deliverable=multipart-${{ matrix.os }}" >> $env:GITHUB_ENV
        if: ${{ startsWith(matrix.os, 'windows') }}go
      - name: Create release
        run: ./scripts/build.sh
        env:
          GO_BUILD_DELIVERABLE: ${{ env.multipart-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: ${{ matrix.shasum }}
        if: ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Create release windows
        shell: cmd
        run: |
          echo "GITHUB_TAG: '${{ github.ref }}'"
          echo "MULTIPART_DELIVERABLE: '${{ env.multipart-deliverable }}'"
          cd cmd/multipart
          go build -buildvcs=false -ldflags "-X main.Version=${{ github.ref }}" -o "${{ env.multipart-deliverable }}"
          sha512sum "${{ env.multipart-deliverable }}" > "${{ env.multipart-deliverable }}.sha512.txt"
          chmod +x "${{ env.multipart-deliverable }}"
          ls multipart-windows-2019
        if: ${{ startsWith(matrix.os, 'windows') }}
        # yamllint enable rule:line-length
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/multipart/${{ env.multipart-deliverable }}
          asset_name: ${{ env.multipart-deliverable }}
          tag: ${{ github.ref }}
      - name: Upload checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/multipart/${{ env.multipart-deliverable }}.sha512.txt
          asset_name: ${{ env.multipart-deliverable }}.sha512.txt
          tag: ${{ github.ref }}
